---
- name:  Create /xroad directory
  become: yes
  file: path=/xroad state=directory mode=0755

- include: ubuntu.yml
  when: ansible_os_family == "Debian"

- include: rhel.yml
  when: ansible_os_family == "RedHat"
