- name: build docker image for building deb packages 
  docker_image:
    name: docker-debbuild 
    path: ../src/packages/docker-debbuild
    force: yes

- name: build deb packages in docker
  docker_container:
    name: docker-debbuild 
    image: docker-debbuild 
    state: started
    restart: true
    detach: false
    cleanup: yes
    user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
    env:
        HOME: "/workspace/src/packages"
    volumes: 
      - ..:/workspace
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: "/workspace/src/deb-docker.sh"

- name: build docker image for building RPM packages
  docker_image:
    name: docker-rpmbuild
    path: ../src/packages/docker-rpmbuild
    force: yes
  tags: rpm

- name: build RPM packages in docker
  docker_container:
    name: docker-rpmbuild
    image: docker-rpmbuild
    state: started
    restart: true
    detach: false
    cleanup: yes
    user: "{{ ansible_user_uid }}:{{ ansible_user_gid }}"
    env:
        HOME: "/workspace/src/packages"
    volumes:
      - ..:/workspace
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    command: "/workspace/src/rpm-docker.sh"
  tags: rpm
