# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "forwarded_port", guest: 8081, host: 8081

  config.vm.synced_folder "./xroad-src", "/build"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    cd /build && ./prepare_buildhost.sh && ./update_ruby_dependencies.sh && ./build_packages.sh
  SHELL
end
