---
- name: Copy to security server
  become: yes
  copy: src={{item}} dest=/xroad/ force=no
  with_fileglob:
    - ../src/packages/xroad-*deb

- name: Ensure dpkg-dev
  become: yes
  apt: name=dpkg-dev state=present

- name: Scan new packages
  become: yes
  shell: dpkg-scanpackages . /dev/null | gzip -c9 > Packages.gz
  args:
    chdir: /xroad
